sudo: true
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get -qq update;
      sudo apt-get -qq install g++-4.8;
      export CXX='g++-4.8';
      sudo apt-get install -qq debhelper autotools-dev cups-ppdc libcups2-dev cups imagemagick ghostscript;
    fi
  - "export JOBS=4"
  - npm install -g node-gyp
before_script:
  - npm prune
script:
  - npm test

after_success:
  - npm run coverage

branches:
  only:
    - master
    - /^greenkeeper-.*$/
    - /^greenkeeper/.*$/
os:
  - linux
  - osx
